### ISSUE TITLE
Set up custom domain DNS record

### ISSUE THREAD

**Issue by daniel-j-h** [rowing-social/rowing-social#1]
To make https://rowing.social work, we need to point a DNS record to this Github Page.

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site

https://github.com/rowing-social/rowing-social/settings/pages

Next actions
- [x] Set DNS record
- [x] Enable TLS in project settings

**Comment by daniel-j-h** [comment]
Quick sketch,

![Screenshot from 2021-12-27 20-46-10](https://user-images.githubusercontent.com/527241/147502781-91fe1d63-152b-4a09-9629-18f6cc1977ef.png)

![Screenshot from 2021-12-27 20-46-33](https://user-images.githubusercontent.com/527241/147502780-dd2fb056-ac65-42fd-a9cb-cf3c2bfacbcd.png)

**Comment by ucyo** [comment]
DNS setup complete.. waiting to propagate.. ❤️ by rowers, for rowers ❤️

**Comment by daniel-j-h** [comment]
Super! Works! :bow:
